# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: CrateRotaryPhone
  parent: CrateGenericSteel
  name: rotary phone crate
  description: A crate with 5 phones inside, prank calls are a punishable offense
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: RotaryPhoneFlatPack
        amount: 5

- type: entity
  parent: CrateHydroSecure
  id: CrateServiceCoconutCrab
  name: coconut crab crate
  description: This is crabtually insane!
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: MobCoconutCrab
          amount: 1
        - id: MobCrabTiny
          amount: 6

- type: entity
  parent: CrateGenericSteel
  id: CratePlantBGoneSpray
  name: bulk Plant-B-Gone spray crate
  description: From Monstano. "Unwanted Weeds, Meet Your Celestial Roundup!"
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: PlantBGoneSpray
        amount: 20

- type: entity
  parent: CratePlastic
  id: CrateHolySuppliesAdvanced
  name: advanced holy supplies crate
  description: Contains holy supplies for religious needs
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: JugHolyWater
          amount: 2
        - id: BoxCandle
          amount: 2
        - id: BoxCandleSmall
          amount: 2
        - id: Urn
          amount: 2
        - id: SpiritCandle
        - id: FoodShakerSalt
          amount: 4

- type: entity
  parent: CrateHydroSecure
  id: CrateRanchingSupplies
  name: ranching supplies crate
  description: Contains all the necessary supplies to start ranching, Food not included
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: IncubatorFlatpack
          amount: 4
        - id: WhiteEgg
          amount: 4
        - id: ChickenCarrier
          amount: 2
        - id: ClothingBeltRancher
          amount: 2
