# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: BloodCultist
  name: roles-antag-blood-cultist-name
  antagonist: true
  setPreference: true
  objective: roles-antag-blood-cultist-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 2h

- type: antagSpecifier
  abstract: true
  parent: RestrictedAntag
  id: BaseBloodCult
  jobBlacklist: [ Chaplain ]
  briefing:
    text: blood-cult-role-greeting
    color: Red
    sound: "/Audio/_Trauma/BloodCult/blood_cult_greeting.ogg"
  startingGear: BloodCultistGear
  prefRoles: [ BloodCultist ]

- type: antagSpecifier
  parent: BaseBloodCult
  id: BloodCultist
  mindRoles: [ MindRoleBloodCultist ]

- type: antagSpecifier
  parent: BaseBloodCult
  id: BloodCultLeader
  mindRoles: [ MindRoleBloodCultLeader ]

- type: antagSpecifier
  parent: BaseBloodCult
  id: BloodCultConstruct
  startingGear: null
  mindRoles: [ MindRoleBloodCultConstruct ]

- type: startingGear
  id: BloodCultistGear
  storage:
    back:
    - RitualDagger
    - RunedMetal20

- type: antagSmite
  id: BloodCultist
  antag: BloodCultist
  rule: BloodCult
  ruleComp: BloodCultRule
  icon:
    sprite: Objects/Weapons/Melee/cult_dagger.rsi
    state: icon
