# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  abstract: true
  id: AlertLevelLock
  components:
  - type: StationAlertLevelLock
    lockedAlertLevels:
    - Green
    - Blue
    - Yellow

- type: entity
  abstract: true
  id: AntiTamper
  components:
  - type: Speech
    speechSounds: Pai
  - type: WiresPanel
    openingTool: Prying
  - type: WiresVisuals
  - type: UserInterface
    interfaces:
      enum.WiresUiKey.Key:
        type: WiresBoundUserInterface
  - type: AntiTamper


- type: entity
  abstract: true
  parent: AntiTamper
  id: AntiTamperLowPriority
  components:
  - type: AntiTamper
    yellAlertType: OnDestroyed
    alarmAlertType: OnDestroyed
    alarmSound:
      path: /Audio/Machines/warning_buzzer.ogg
      params:
        volume: 1
    examineText: It is equipped with a basic tamper-detection device.
  - type: Wires
    layoutId: SecureStorageLowPriority
    boardName: wires-board-name-secure-storage

- type: entity
  abstract: true
  parent: AntiTamper
  id: AntiTamperHighPriority
  components:
  - type: AntiTamper
    yellAlertType: All
    alarmAlertType: OnDestroyed
    alarmSound:
      path: /Audio/Machines/warning_buzzer.ogg
      params:
        volume: 5
    examineText: It is equipped with an advanced tamper-detection device.
    broadcastChannel: Command
  - type: Wires
    layoutId: SecureStorageHighPriority
    boardName: wires-board-name-secure-storage
