# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Chemist
  guides:
  - Chemicals
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipEducation
    - SkillChipChemist
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      speedModifier: 1.25

- type: startingGear
  id: ChemistGear
  equipment:
    belt: ChemBagFilled
