# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: BaseMachineCircuitboard
  id: DeepFryerCircuitboard
  name: deep fryer machine board
  description: A machine printed circuit board for a deep fryer.
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: KitchenDeepFryer
    stackRequirements:
      Manipulator: 1
      Steel: 10
      CableHV: 4

- type: entity
  parent: BaseMachineCircuitboard
  id: ChemiCompilerMachineCircuitboard
  name: ChemiCompiler M7 machine board
  description: A machine printed circuit board for a ChemiCompiler M7.
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: ChemiCompiler
    stackRequirements:
      Manipulator: 2
      Glass: 2
      Cable: 2
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker

- type: entity
  parent: BaseMachineCircuitboard
  id: AbductorBiofabMachineBoard
  name: abductor biofab machine board
  description: A machine printed circuit board for a abductor biofab.
  components:
  - type: MachineBoard
    prototype: AbductorBiofabricator
    stackRequirements:
      Manipulator: 4
