// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.CombatMode;
using Content.Shared.Weapons.Melee;
using Content.Trauma.Shared.Forging;

namespace Content.IntegrationTests.Tests._Trauma;

public sealed partial class ForgingTest : GameTest
{
    private static readonly EntProtoId Hammer = "MeleeHammer";
    private static readonly EntProtoId MobDwarf = "MobDwarf";

    /*
    [SidedDependency(Side.Server)] private ForgingSystem _forging = default!;
    [SidedDependency(Side.Server)] private SharedCombatModeSystem _combat = default!;
    [SidedDependency(Side.Server)] private SharedMeleeWeaponSystem _melee = default!;
    */

    /// <summary>
    /// Checks that all forged item prototypes are sane and that there are no empty categories.
    /// </summary>
    [Test]
    public async Task AllForgedItemsValidTest()
    {
        var factory = SEntMan.ComponentFactory;
        var metallicName = factory.CompName<MetallicComponent>();
        Assert.Multiple(() =>
        {
            var used = new HashSet<ProtoId<ForgingCategoryPrototype>>();
            // sanity check each item prototype
            foreach (var item in SProtoMan.EnumeratePrototypes<ForgedItemPrototype>())
            {
                used.Add(item.Category);

                if (item.Result is {} result)
                {
                    var entity = SProtoMan.Index(result);
                    Assert.That(entity.HasComp(metallicName),
                        $"Result of forging {item.ID}, {result}, must inherit from BaseMetallic!");
                }
                else if (item.Sprite != null)
                {
                    Assert.That(item.Name, Is.Not.EqualTo(string.Empty), $"Forged item {item.ID} must set a name since it is procedurally generated!");
                    if (item.Construction != null)
                    {
                        Assert.That(item.Finished, Is.Not.Null, $"Forged item {item.ID} must have a finished item for its procedural construction graph!");
                    }
                }
                else
                {
                    Assert.Fail($"Result of forging {item.ID} must either be procedurally generated by sprite or a specified result entity!");
                }
            }

            // now check that all categories are used, i.e. not empty
            foreach (var category in SProtoMan.EnumeratePrototypes<ForgingCategoryPrototype>())
            {
                Assert.That(used.Contains(category.ID), $"Forging category {category.ID} is not used by any items!");
            }
        });
    }

    /* TODO: fix it running forever
    /// <summary>
    /// Forges every item from every allowed material.
    /// Doesn't attempt construction for items that e.g. need a handle.
    /// </summary>
    [Test]
    public async Task SpawnForgedItemsTest()
    {
        var map = await Pair.CreateTestMap();
        var coords = map.GridCoords;
        await Server.WaitAssertion(() =>
        {
            var dorf = SSpawn(MobDwarf, coords);
            var hammer = SSpawn(Hammer, coords); // this assumes a hammer will never degrade over time
            var weapon = SComp<MeleeWeaponComponent>(hammer);
            _combat.SetInCombatMode(dorf, true);
            Assert.Multiple(() =>
            {
                foreach (var item in SProtoMan.EnumeratePrototypes<ForgedItemPrototype>())
                {
                    foreach (var metal in SProtoMan.EnumeratePrototypes<MetalPrototype>())
                    {
                        if (!_forging.CanMakeFrom(item, metal.ID))
                            continue;

                        var uid = _forging.SpawnUnfinished(coords, metal.ID, item.ID, 1);
                        var workable = SComp<WorkableComponent>(uid);
                        while (workable.Remaining > 0)
                        {
                            var last = workable.Remaining;
                            weapon.NextAttack = TimeSpan.Zero; // bonk
                            _melee.AttemptLightAttack(dorf, hammer, weapon, uid, canParry: false);
                            Assert.That(workable.Remaining, Is.LessThan(last), $"Hitting {SPrettyString(uid)} with a hammer didn't help work it");
                        }

                        Assert.That(SEntMan.IsQueuedForDeletion(uid), $"{SPrettyString(uid)} was not deleted after working it");
                    }
                }
            });
        });
    }
    */
}
