# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleLoneAbductor
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: LoneAbductorAntag
    roleType: SoloAntagonist
    subtype: role-subtype-abductor
  - type: Abductor # TODO: see if anything actually checks this...
  - type: AbductorRole

- type: entity
  parent: MindRoleLoneAbductor
  id: MindRoleAbductorAgent
  name: Abductor Agent Role
  components:
  - type: MindRole
    antagPrototype: AbductorAgentAntag
    roleType: TeamAntagonist

- type: entity
  parent: MindRoleLoneAbductor
  id: MindRoleAbductorScientist
  name: Abductor Scientist Role
  components:
  - type: MindRole
    antagPrototype: AbductorScientistAntag
    roleType: TeamAntagonist

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorVictim
  name: Abductee Role
  components:
  - type: MindRole
    roleType: AbductorVictimRole
    antagPrototype: AbductorVictimAntag
    subtype: role-subtype-abductor-victim
  - type: AbductorVictim
