// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.StatusIcon;
using Content.Shared.Whitelist;
using Content.Trauma.Shared.CosmicCult.Prototypes;
using Robust.Shared.Audio;

namespace Content.Trauma.Shared.CosmicCult.Components;

/// <summary>
/// Added to entities to tag that they are a cosmic cultist. Holds nearly all cultist-relevant data! Removal of this component is used to call for a deconversion
/// </summary>
[RegisterComponent, NetworkedComponent]
[AutoGenerateComponentState(fieldDeltas: true)]
public sealed partial class CosmicCultComponent : Component
{
    #region Housekeeping

    /// <summary>
    /// The status icon prototype displayed for cosmic cultists.
    /// </summary>
    [DataField]
    public ProtoId<StatusIconPrototype> StatusIcon = "CosmicCultIcon";
    #endregion

    #region Ability Data
    [DataField, AutoNetworkedField]
    public HashSet<ProtoId<InfluencePrototype>> UnlockedInfluences = [];

    [DataField]
    public EntProtoId SiphonAction = "ActionCosmicSiphon";

    [DataField]
    public EntProtoId CosmicFragmentationAction = "ActionCosmicFragmentation";

    [DataField]
    public EntProtoId ShopAction = "ActionCosmicShop";

    [DataField, AutoNetworkedField]
    public EntityUid? SiphonActionEntity;

    [DataField, AutoNetworkedField]
    public EntityUid? CosmicFragmentationActionEntity;

    [DataField, AutoNetworkedField]
    public EntityUid? ShopActionEntity;

    [DataField]
    public EntProtoId MonumentAction = "ActionCosmicPlaceMonument";

    [DataField, AutoNetworkedField]
    public EntityUid? MonumentActionEntity;

    /// <summary>
    /// Actions added by bought influences, removed if you respec.
    /// </summary>
    [DataField, AutoNetworkedField]
    public List<EntityUid> BoughtActions = [];

    [DataField, AutoNetworkedField]
    public HashSet<ProtoId<InfluencePrototype>> OwnedInfluences = [];

    /// <summary>
    /// How many times this cultist can respec. Someone will abuse the hell out of it eventually.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int RespecsAvailable;

    /// <summary>
    /// The duration of the doAfter for Siphon Entropy
    /// </summary>
    [DataField]
    public TimeSpan CosmicSiphonDelay = TimeSpan.FromSeconds(2.5f);

    /// <summary>
    /// The duration of the doAfter (and stun) for Shatter Cognition
    /// </summary>
    [DataField]
    public TimeSpan CosmicConversionDelay = TimeSpan.FromSeconds(6f);

    /// <summary>
    /// The duration of the doAfter for Shunt Subjectivity
    /// </summary>
    [DataField]
    public TimeSpan CosmicBlankDelay = TimeSpan.FromSeconds(1.2f);

    /// <summary>
    /// The duration of Shunt Subjectivity's trip to the cosmic void
    /// </summary>
    [DataField]
    public TimeSpan CosmicBlankDuration = TimeSpan.FromSeconds(15);

    /// <summary>
    /// The duration of Vacuous Imposition's shield.
    /// </summary>
    [DataField]
    public TimeSpan CosmicImpositionDuration = TimeSpan.FromSeconds(5.8);

    /// <summary>
    /// The duration of Astral Stride.
    /// </summary>
    [DataField]
    public TimeSpan CosmicStrideDuration = TimeSpan.FromSeconds(4.6);

    /// <summary>
    /// The duration of Null Glare's flash/disorientation.
    /// </summary>
    [DataField]
    public TimeSpan CosmicGlareDuration = TimeSpan.FromSeconds(4f);

    /// <summary>
    /// The range of Null Glare.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int CosmicGlareRange = 6;

    /// <summary>
    /// The movement speed penalty inflicted by Null Glare.
    /// </summary>
    [DataField]
    public float CosmicGlarePenalty = 0.7f;

    /// <summary>
    /// The stun duration inflicted by Null Glare.
    /// </summary>
    [DataField, AutoNetworkedField]
    public TimeSpan? CosmicGlareStun;

    /// <summary>
    /// The amount of Entropy generated by Siphon Entropy
    /// </summary>
    [DataField, AutoNetworkedField]
    public int CosmicSiphonQuantity = 1;

    /// <summary>
    /// Additional entropy generated by Siphon Entropy when used on critical targets (it kills them)
    /// </summary>
    [DataField, AutoNetworkedField]
    public int CosmicSiphonQuantityCrit = 5;

    /// <summary>
    /// Additional entropy generated by Siphon Entropy when used on critical high-value targets
    /// </summary>
    [DataField, AutoNetworkedField]
    public int CosmicSiphonQuantityCritHighValue = 8;

    /// <summary>
    ///     What entities are considered "high value" by Siphon Entropy
    /// </summary>
    [DataField]
    public EntityWhitelist HighValueTargetWhitelist = new() { Components = ["MindShield", "BibleUser"] }; // You can just... do that, apparently
    #endregion

    #region Misc Data
    /// <summary>
    /// The cultist's current level. Replaces monument stages.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int CurrentLevel;

    [DataField]
    public int MaxLevel = 3;

    /// <summary>
    /// The whole cult's tier. Used for UI prediciton.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int CultTier;

    /// <summary>
    /// For prediction purposes. How many cultists need to get the next level in order for the cult's level to increase.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int CultistsForNextLevel;

    /// <summary>
    /// Wether the cultist can get any more entropy than they have.
    /// </summary>
    [DataField, AutoNetworkedField]
    public bool EntropyLocked;

    /// <summary>
    /// Wether we are waiting for the player to confirm leveling up.
    /// </summary>
    [DataField, AutoNetworkedField]
    public bool LevelUpAwaitingConfirmation;

    /// <summary>
    /// The probability that siphoning entropy while empowered will cause lights to flicker.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float FlickerProbability = 0.20f;

    /// <summary>
    /// The probability that siphoning entropy while empowered will cause lights to flicker.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float FlickerRange = 5f;

    /// <summary>
    /// The amount of Entropy the user is allowed to spend.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int EntropyBudget;

    /// <summary>
    /// The total amount of Entropy the user collected.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int TotalEntropy;

    /// <summary>
    /// The amount of Entropy the user needs to progress to the next level. Increases by <see cref="EntropyLevelRequirementIncrease"/> on every level.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int EntropyForNextLevel = 10;

    [DataField]
    public int EntropyLevelRequirementIncrease = 10;

    /// <summary>
    /// BUI stuff.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int EntropyRequirementOffset;

    /// <summary>
    /// Goobstation Change - Shitchap: Whether or not this cultist was weak to holy before conversion.
    /// </summary>
    [DataField, AutoNetworkedField]
    public bool WasWeakToHoly;

    /// <summary>
    /// Wether or not this cultist has been empowered by a Malign Rift.
    /// </summary>
    [DataField, AutoNetworkedField]
    public bool CosmicEmpowered;

    #endregion

    #region VFX & SFX
    [DataField]
    public EntProtoId LapseVFX = "CosmicLapseAbilityVFX";

    [DataField]
    public EntProtoId GlareVFX = "CosmicGlareAbilityVFX";

    [DataField]
    public EntProtoId AbsorbVFX = "CosmicGenericVFX";

    [DataField]
    public EntProtoId ImpositionVFX = "CosmicImpositionAbilityVFX";

    [DataField]
    public EntProtoId CosmicEchoVfx = "CosmicEchoVfx";
    public EntProtoId TransmuteVFX = "CosmicGenericVFX";

    [DataField]
    public SoundSpecifier IngressSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/ability_ingress.ogg");

    [DataField]
    public SoundSpecifier GlareSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/ability_glare.ogg");

    [DataField]
    public SoundSpecifier NovaCastSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/ability_nova_cast.ogg");

    [DataField]
    public SoundSpecifier ImpositionSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/ability_imposition.ogg");
    [DataField]
    public SoundSpecifier TransmuteSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/glyph_trigger.ogg");
    public SoundSpecifier StrideSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/ability_stride.ogg");
    #endregion
}
