// <Trauma>
using Content.Trauma.Common.CartridgeLoader.Cartridges;
// </Trauma>
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LogProbeUiFragment : BoxContainer
{
    // <Trauma>
    public static Action<LogProbeUiFragment>? OnCreated;
    public Action<NanoChatData>? OnSetupNanoChatView;
    public Action<NanoChatData>? OnDisplayNanoChat;
    public Action? OnSetupAccessLogView;
    public Action<List<PulledAccessLog>>? OnDisplayAccessLogs;
    // </Trauma>

    /// <summary>
    /// Action invoked when the print button gets pressed.
    /// </summary>
    public Action? OnPrintPressed;

    public LogProbeUiFragment()
    {
        RobustXamlLoader.Load(this);

        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
        // <Trauma>
        OnCreated?.Invoke(this);
        // </Trauma>
    }

    // <DeltaV> - Update to handle both types of data
    public void UpdateState(LogProbeUiState state)
    {
        EntityName.Text = state.EntityName;
        PrintButton.Disabled = string.IsNullOrEmpty(state.EntityName);

        ProbedDeviceContainer.RemoveAllChildren();

        if (state.NanoChatData is { } nano)
        {
            OnSetupNanoChatView?.Invoke(nano);
            OnDisplayNanoChat?.Invoke(nano);
        }
        else
        {
            OnSetupAccessLogView?.Invoke();
            if (state.PulledLogs.Count > 0)
                OnDisplayAccessLogs?.Invoke(state.PulledLogs);
        }
    }

    // <DeltaV> - Changed to public
    public void AddAccessLog(PulledAccessLog log, int numberLabelText)
    {
        var timeLabelText = TimeSpan.FromSeconds(Math.Truncate(log.Time.TotalSeconds)).ToString();
        var accessorLabelText = log.Accessor;
        var entry = new LogProbeUiEntry(numberLabelText, timeLabelText, accessorLabelText);

        ProbedDeviceContainer.AddChild(entry);
    }
}
