using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class CharacterWindow : DefaultWindow
{
    // <Trauma>
    public static event Action<CharacterWindow>? OnOpened;
    // </Trauma>
    public CharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }

    // <Trauma>
    protected override void Opened()
    {
        base.Opened();
        OnOpened?.Invoke(this);
    }
    // </Trauma>
}
