[game]
role_timers = true
role_timer_override = "Trauma"
round_end_pvs_overrides = true
lobbyduration = 180
fallbackpreset = "Traitor,Survival,Extended"
#minimum_job_fallback = "SameDepartment" # re-enable if it gets fixed

[chat]
max_announcement_length = 512

[voice]
barks_enabled = true

[shuttle]
cooldown = 5

[net]
pvs_enter_budget = 300 # 200 by default
log_late_msg = false # pointless log spam why is this on in release

[adminlogs]
high_log_playtime = 2 # this kills the raider

[afk]
time = 1500 # 25m
confirm_timeout = 90 # 1.5m

[playtest]
explosion_damage_modifier = 0.3

[biomass]
easy_mode = false # woodchipper is actually dangerous

[ic]
ssd_sleep = false # chuddy and doesnt account for NPCs
flavor_text = true # Born to larp

[infolinks]
bug_report = "https://github.com/Trauma-Station/Trauma-Station/issues/created_by/choose"
discord    = "https://discord.traumastation.com"
github     = "https://github.com/Trauma-Station/Trauma-Station"
wiki       = "https://wiki.traumastation.com"
