# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: ChiefEngineer
  antagAdvantage: 75
  guides:
  - Engineering
  access:
  - Robotics
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipEchelonEducation
    - SkillChipDatabase
    - SkillChipTool
  - !type:AddComponentSpecial
    components:
    - type: Condemned # Nanotrasen owns your soul pal.
      soulOwnedNotDevil: true
    - type: EngineeringStaff

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    ears: ClothingHeadsetAltEngineering
  storage:
    back:
    - TelescopicBaton
