# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: StationEngineer
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipEducation
    - SkillChipDatabase
    - SkillChipTool
  - !type:AddComponentSpecial
    components:
    - type: EngineeringStaff
