# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: TechnicalAssistant
  guides:
  - Construction
  - Power
  - Networking
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipEducation
    - SkillChipDatabase
  - !type:AddComponentSpecial
    components:
    - type: EngineeringStaff
