# SPDX-License-Identifier: AGPL-3.0-or-later

- type: statusIcon
  id: MindShieldBrokenIcon
  priority: 2
  locationPreference: Right
  layer: Mod
  isShaded: true
  icon:
    sprite: /Textures/_Goobstation/Interface/Misc/security_icons.rsi
    state: MindShield-broken

- type: statusIcon
  parent: SecurityIcon
  id: SecurityIconPerma
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_perma

- type: statusIcon
  parent: SecurityIcon
  id: SecurityIconSearch
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_search
