# SPDX-License-Identifier: AGPL-3.0-or-later

- type: jobRequirementOverride
  id: Trauma
  jobs:
    # Dignitary
    NanotrasenRepresentative:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 5h
    # Command
    Captain:
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 2h
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 2h
    - !type:RoleTimeRequirement
      role: JobQuartermaster
      time: 2h
    - !type:RoleTimeRequirement
      role: JobResearchDirector
      time: 2h
    - !type:RoleTimeRequirement
      role: JobChiefEngineer
      time: 2h
    Quartermaster:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 5h
    HeadOfPersonnel:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Service
      time: 5h
    ChiefEngineer:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 5h
    ChiefMedicalOfficer:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 5h
    ResearchDirector:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 5h
    HeadOfSecurity:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 5h
    #Intern
    SecurityCadet:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 5h
      inverted: true
    - !type:OverallPlaytimeRequirement
      time: 2h
    TechnicalAssistant:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 5h
      inverted: true
    MedicalIntern:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 5h
      inverted: true
    ResearchAssistant:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 5h
      inverted: true
    ServiceWorker:
    # consider removing this if it gets turned into waiter
    - !type:DepartmentTimeRequirement
      department: Service
      time: 5h
      inverted: true
    #Assistant made into a learner role, D-Class the new assistant role
    Passenger:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 8h
      inverted: true # Out into the cold with you
    # Service
    Chef: # Anti-raider ops
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 1h
    Bartender: []
    # Cargo
    SalvageSpecialist:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 2h
    # Engineering
    StationEngineer:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 2h
    AtmosphericTechnician:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 2h
    # Medical
    Chemist:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h
    MedicalDoctor:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h
    Paramedic:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h
    # Science
    Scientist:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 2h
    # Security
    SecurityOfficer:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2h
    Detective:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2h
    Warden:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 4h # muh intermediary role, also kinda has to know a bit more law.
    # Silicon
    StationAi:
    - !type:RoleTimeRequirement
      role: JobBorg
      time: 5h
    Borg:
    - !type:OverallPlaytimeRequirement
      time: 2h
  antags:
    Changeling:
    - !type:OverallPlaytimeRequirement
      time: 5h
    HeadRev:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 5h
    InitialInfected:
    - !type:OverallPlaytimeRequirement
      time: 1h
    - &biological_requirement
      !type:SpeciesRequirement
      inverted: true
      species:
      - IPC
      - Plasmaman
    Nukeops:
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2h
    NukeopsMedic:
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2h
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 2h
    NukeopsCommander:
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 3h
    SpaceNinja:
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2h
    - *biological_requirement
    Wizard:
    - !type:OverallPlaytimeRequirement
      time: 5h
    MothershipCore:
    - !type:RoleTimeRequirement
      role: JobStationAi
      time: 5h
    Xenoborg:
    - !type:RoleTimeRequirement
      role: JobBorg
      time: 5h
    Zombie:
    - *biological_requirement
