# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Bartender
  guides:
  - Drinks
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipEducation
    - SkillChipShotgun
    - SkillChipUnarmed
