# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Chef
  guides:
  - FoodRecipes
  - CQC
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipEducation
    - SkillChipShortBlade
    - SkillChipChef

- type: startingGear
  id: ChefGear
  storage:
    back:
    - IngredientsBeacon
