# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: RiceBushel
  components:
  - type: Tag
    tags:
    - Ruminant
    - Rice

- type: entity
  id: FoodMimana
  components:
  - type: Tag
    tags:
    - Fruit
    - Mimana
