# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: ParadoxClone
  creditImage: /Textures/_Trauma/EndCredits/Antags/paradox.png

- type: antagSpecifier
  id: ParadoxClone
  roleLoadout:
  - RoleSurvivalPlasmaTank
