# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Wizard
  objective: roles-antag-wizard-description-goob
  creditImage: /Textures/_Trauma/EndCredits/Antags/wizard.png
  setPreference: true
  tags:
  - Roundstart

- type: antagSpecifier
  id: Wizard
  startingGear: WizardGear
  unequipOldGear: true
  prefRoles: [ Wizard ]
  components:
  - type: Wizard
  - type: LanguageSpeaker
    speaks: []
    understands: []
  - type: UniversalLanguageSpeaker
  - type: TowerOfBabel
