# SPDX-License-Identifier: AGPL-3.0-or-later

# Hunters
  # SyndiePol
- type: startingGear
  id: HunterAntagGearSpacepol
  equipment:
    head: ClothingHeadHelmetSwat # maybe keep justice for shits and giggles?
    eyes: ClothingEyesGlassesSecurity
    neck: Dinkystar
    mask: ClothingHunterMaskGasSwat
    jumpsuit: ClothingUniformJumpsuitNanotrasen
    outerClothing: ClothingOuterArmourDurathread
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsJackFilled
    belt: ClothingBeltSecurityFilled
    id: HunterPDA
    pocket1: WeaponPistolMk58
    pocket2: WeaponLaserSidearm
    ears: ClothingHeadsetAltHunter
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - BoxSurvivalSlotsSecurity
    - MagazinePistol
    - ForensicScanner
    - MedkitCombatFilled

- type: antagSpecifier
  id: FugitiveHunterSyndicate
  spawnerPrototype: SpawnPointGhostRoleHunterSpacepol
  startingGear: HunterAntagGearSpacepol
  briefing:
    text: hunter-syndicate-role-greeting
    color: red
  components:
  - type: NpcFactionMember
    factions:
    - Syndicate
  - type: AutoImplant
    implants:
    - DeathAcidifierImplant
  - type: RandomMetadata
  mindRoles:
  - MindRoleGhostRoleHunter

# Spacepol

- type: antagSpecifier
  id: FugitiveHunterSpacepol
  spawnerPrototype: SpawnPointGhostRoleHunterSpacepol
  startingGear: HunterAntagGearSpacepol
  briefing:
    text: hunter-spacepol-role-greeting
    color: red
  components:
  - type: RandomMetadata
  mindRoles:
  - MindRoleGhostRoleHunter

# Russians

- type: startingGear
  id: HunterAntagGearRussian
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatUshanka
    eyes: ClothingEyesGlassesSunglasses
    mask: KnittedBalaclava
    outerClothing: ClothingOuterCoatBomber
    back: ClothingBackpackSatchelLeather
    id: AgentIDCard
    ears: ClothingHeadsetAltFreelancer
    gloves: ClothingHandsGlovesCombat
    neck: ClothingNeckBombCollarBroken
    belt: ClothingBeltUtilityEngineering
  storage:
    back:
    - Stunprod
    - BarbHandcuffs
    - ForensicScanner

- type: antagSpecifier
  id: FugitiveHunterRussian
  spawnerPrototype: SpawnPointGhostRoleHunterRussian
  startingGear: HunterAntagGearRussian
  briefing:
    text: hunter-spacepol-role-greeting
    color: red
  components:
  - type: RandomMetadata
  mindRoles:
  - MindRoleGhostRoleHunter
# Bounty Hunter

- type: startingGear
  id: HunterAntagGearBounty
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryContractor
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCorpsoft
    eyes: ClothingEyesThermalVisionGogglesSyndie
    outerClothing: ClothingOuterCoatJacketLeather
    back: ClothingBackpackRev
    id: AgentIDCard
    ears: ClothingHeadsetAltFreelancer
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltSecurityWebbingFilled
  storage:
    back:
    - Katana
    - WeaponRevolverDeckard
    - ForensicScanner
    - FoodBurgerMcrib

- type: antagSpecifier
  id: FugitiveHunterBounty
  spawnerPrototype: SpawnPointGhostRoleHunterBounty
  startingGear: HunterAntagGearBounty
  briefing:
    text: hunter-spacepol-role-greeting
    color: red
  components:
  - type: RandomMetadata
  mindRoles:
  - MindRoleGhostRoleHunter

# Fugitives
  # Convict
- type: startingGear
  id: FugitiveAntagGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
    belt: ClothingBeltStorageWaistbag
    id: IDCardTide
    pocket1: CombatKnife
    pocket2: SoapSyndie
  inhand:
  - SatchelFugitive
  storage:
    belt:
    - BarberScissors
    - Telecrystal25
    - BaseUplinkRadio

- type: antagSpecifier
  id: Fugitive
  spawnerPrototype: SpawnPointGhostRoleFugitive
  startingGear: FugitiveAntagGear
  briefing:
    text: fugitive-role-greeting
    color: red
  components:
  - type: NpcFactionMember
    factions:
    - Syndicate
  - type: RandomMetadata
  - type: EmitSoundOnSpawn # fell out of the ceiling
    sound: /Audio/Effects/clang.ogg
  mindRoles:
  - MindRoleGhostRoleFugitive
