# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: BaseMindRoleAntag
  id: DevilMindRole
  name: Devil Role
  components:
  - type: MindRole
    antagPrototype: Devil
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-devil
  - type: DevilRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHeretic
  name: Heretic Role
  components:
  - type: MindRole
    antagPrototype: Heretic
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-heretic
  - type: HereticRole
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
        interactionRange: 0 # no range or validation because it's on the role and would immediately get closed
        requireInputValidation: false
  - type: Store
    name: store-preset-name-heretic
    categories:
    - HereticPathAsh
    - HereticPathLock
    - HereticPathFlesh
    - HereticPathBlade
    - HereticPathVoid
    - HereticPathRust
    - HereticPathCosmos
    - HereticPathSpecial
    - HereticPathSideT1
    - HereticPathSideT2
    - HereticPathSideT3
    currencyWhitelist:
    - KnowledgePoint
    - SideKnowledgePoint
    balance:
      SideKnowledgePoint: 1

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleGhoul
  name: Ghoul
  components:
  - type: MindRole
    antagPrototype: Ghoul
    exclusiveAntag: false
    roleType: TeamAntagonist
    subtype: role-subtype-ghoul
  - type: GhoulRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleArenaParticipant
  name: Arena Participant
  components:
  - type: MindRole
    antagPrototype: ArenaParticipant
    exclusiveAntag: false
    roleType: SoloAntagonist
    subtype: role-subtype-arena-participant
  - type: HereticArenaParticipantRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBrainwashed
  name: Brainwashed Role
  components:
  - type: MindRole
    antagPrototype: Mindcontrolled
    exclusiveAntag: true
    roleType: Familiar
    subtype: role-subtype-brainwashed
  - type: MindcontrolledRole

- type: entity
  parent: MindRoleChangeling
  id: MindRoleChangelingmidround
  name: Sleeper Changeling Role
  components:
  - type: MindRole
    exclusiveAntag: false           #  bastard experiment

- type: entity
  parent: MindRoleHeretic
  id: MindRoleHereticmidround
  name: Sleeper Heretic Role
  components:
  - type: MindRole
    exclusiveAntag: false   # bastard experiment

- type: entity
  parent: DevilMindRole
  id: DevilMindRolemidround
  name: Sleeper Devil Role

# Slasher
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSlasher
  name: Slasher Role
  components:
  - type: MindRole
    antagPrototype: Slasher
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-slasher

#contractor
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleContractor
  name: Contractor Role
  components:
  - type: MindRole
    antagPrototype: Contractor
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-contractor
