- type: antag
  id: Changeling
  name: roles-antag-changeling-name
  antagonist: true
  setPreference: true
  objective: roles-antag-changeling-objective
  guides: [ Changelings ]
  tags:
  - OnStation
  - Roundstart
  - Unkillable
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 5h

- type: antagSpecifier
  parent: RestrictedAntag
  id: Changeling
  prefRoles: [ Changeling ]
  briefing:
    text: changeling-role-greeting
    color: Red
    sound: /Audio/_Goobstation/Ambience/Antag/changeling_start.ogg # Trauma
  # <Trauma>
  blacklist:
    components:
    - Silicon
    - BorgChassis
  components:
  # removed most of upstreams components, ling is mostly implemented in ChangelingRule shitcode
  - type: Changeling
  - type: DestructionResistance
  - type: RevolutionaryImmune
  - type: ZombieImmune
  # </Trauma>
  mindRoles:
  - MindRoleChangeling
